name: Go
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build
        run: cd backend && go build -o serve server/server.go && cd ..
      - name: Build db
        run: cd backend && go build -o db pkg/db.go && cd ..
    #   - name: Test with the Go CLI
    #     run: go test ./...
  Fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Format backend and db
        run: cd backend && go fmt ./... && cd ..
      # - name: Format db
      #   run: cd database && go fmt ./... && cd ..
    #   - name: Golangci Linter
    #     uses: golangci/golangci-lint-action@v6